---
- name: Change default directory for templates if aixetc_dir is set
  block:
    - name: Load dir stats
      stat:
        path: "{{ aixetc_dir }}"
      register: p
      failed_when:
        - p.stat.exists
        - not p.stat.isdir
    - name: Create directory if not existing
      file: path="{{ aixetc_dir }}" state=directory
      when: not p.stat.exists

    - name: Create required sub-directoires
      file:
        state: directory
        path: "{{ aixetc_dir + item }}"
      loop:
        - "/etc"
        - "/etc/mail"
        - "/etc/security"
        - "/etc/ssh"
  when: aixetc_dir is defined