---
- name: /etc/aliases symlink
  file:
    state: link
    src: /etc/mail/aliases
    dest: /etc/aliases
  when:
    - aixetc_managed_files.etc_mail_aliases is defined
    - aixetc_managed_files.etc_mail_aliases

- name: /etc/syslog.conf log file creation
  block:
    # The reason we run a stat and then a file is that the file will ALWAYS touch a file.
    # This is annoyingly the best way to make this idempotent and only report on CHANGE..
    - name: Check status of syslog.conf log files
      stat: path={{ item.key }}
      register: file_stats
      with_items: "{{ etc_syslogconf | dict2items }}"
    # - debug:
    #     msg: "{{ file_stats | to_nice_json }}"
    #     verbosity: 2
    - name: Create syslog.conf log files that do not exist
      file:
        path: "{{ item }}"
        owner: root
        group: system
        mode: 0640
        state: touch
      with_items: >-
        "{{ file_stats | json_query('results[?stat.exists != `true` ||
          stat.uid != `0` ||
          stat.gr_name != `system` ||
          stat.mode != `0640`].item.key') }}"
      notify: Restart syslogd
    - name: Disable remote logging for syslogd
      shell: >
        (lssrc -Ss syslogd|cut -d: -f3|xargs|grep -q "cmdargs -R") && true || chssys -s syslogd -a "-R"
      when: aixetc_syslogd_disable_remote_logging
      register: syslogd_remote
      changed_when: syslogd_remote.stdout == '0513-077 Subsystem has been changed.'
      notify: Restart syslogd
  when:
    - aixetc_managed_files.etc_syslogconf is defined
    - aixetc_managed_files.etc_syslogconf