---
# handlers file for ansible-role-aix-etc_configs

- name: Restart xntpd
  service:
    name: xntpd
    state: restarted
  when: aixetc_manage_services

- name: Restart syslogd
  service:
    name: syslogd
    state: restarted
  when: aixetc_manage_services

- name: Restart sendmail
  command: refresh -s sendmail
  when: aixetc_manage_services
